app/controllers/orders_controller.rb, app/views/orders/create.html.erb, app/views/orders/index.html.erb, app/views/orders/update.html.erb, config/routes.rb
still need to add references / foreign keys
=> created order controller, model and views

app/models/coin.rb, db/migrate/20190603070533_create_coins.rb, db/schema.rb, test/models/coin_test.rb
=> Added Coin model and table

app/controllers/coins_controller.rb, app/views/coins/index.html.erb, config/routes.rb, test/controllers/coins_controller_test.rb
=> refactored routes to resources

app/controllers/portfolios_controller.rb, app/controllers/positions_controller.rb, app/models/portfolio.rb, app/views/portfolios/new.html.erb
merging two similar branches together
=> set strict form inputs on portfolio page

app/controllers/portfolios_controller.rb, app/controllers/positions_controller.rb, app/models/portfolio.rb, app/views/portfolios/new.html.erb, db/schema.rb
basic form to save portfolio to db complete.
=> can now save portfolio to the db

app/controllers/allocations_controller.rb, app/controllers/portfolios_controller.rb, app/models/portfolio.rb, app/views/allocations/show.html.erb, app/views/shared/_allocations.html.erb, db/schema.rb
sorted out loop failure issue and issue of only saving one allocation instance in the loop
=> updated logic and double render issue

app/controllers/portfolios_controller.rb, app/models/portfolio.rb, app/views/portfolios/show.html.erb, config/routes.rb, db/migrate/20190604054806_change_position_ints_to_floats.rb, db/schema.rb
#36 
Created a method to insert updated positions. Need to make sure the AsOfDt/AsOfDtEnd logic is working correctly next
=> Created controller method to create positions

app/controllers/portfolios_controller.rb, app/views/portfolios/show.html.erb, db/migrate/20190604082402_change_more_ints_to_floats.rb, db/schema.rb
- Added logic to set AsOfDtEnd on position records when new ones are inserted
- Added calculation of portfolio.current_value to be the sum of the positions
- Revised orders.quantity and portfolios.current_value to be floats instead of integers
=> Added AsOfDtEnd logic on positions

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20190604095135_add_columns_to_users.rb, db/schema.rb, db/seeds.rb
- Update users table with First Name, Last Name, API Key, Secret Key
- Added all of the above fields to the sign_up form
- Added set_credentials method to set Binance gem creds to the creds stored on the user
- Added validation to make user email unique
- Added Sign Up action to the nav bar. Removed placeholder links from the nav bar
- Fixing issue where BTC_Price on BTC was set to 0
- All pages will break if there are no credentials set, except for the home page
=> Updated app to use binance keys on user instead of in the dotenv file

app/controllers/portfolios_controller.rb, app/javascript/components/portfolio_chart.js, app/javascript/packs/application.js, app/models/portfolio.rb, app/models/position.rb, app/views/allocations/new.html.erb, app/views/layouts/application.html.erb, app/views/portfolios/show.html.erb, app/views/shared/_allocations.html.erb
Portfolio Show Page
Added table which show last positions calculations.
Added total portfolio values above table
Added JS Chart with intention to show distribution
=> Allocations form and Portfolio show page

app/controllers/portfolios_controller.rb, app/views/portfolios/show.html.erb, db/migrate/20190605023418_add_coin_values_to_positions.rb, db/schema.rb, db/seeds.rb
- Added value_btc and value_usdt to positions instead of storing one value
- Added current_value_btc and current_value_usdt to portfolios instead of storing one value
- Renamed columns
- Updated all references to ensure pages and update positions process was still working
=> Added value_btc columns to positions

Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_chart.scss, app/controllers/portfolios_controller.rb, app/javascript/components/portfolio_chart.js, app/views/portfolios/show.html.erb
updated show page of portfolio and added chart
=> Portfolio chart

Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_portfolio.scss, app/controllers/portfolios_controller.rb, app/javascript/components/portfolio_chart.js, app/models/portfolio.rb, app/views/pages/home.html.erb, app/views/portfolios/edit.html.erb, app/views/portfolios/new.html.erb, app/views/portfolios/show.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_portfolio_form.html.erb
updated portfolio show page and landing page
=> Settingupviews

Gemfile.lock, app/controllers/registrations_controller.rb, config/routes.rb, test/controllers/registrations_controller_test.rb
user now sent directly to portfolio setup page after register
=> Signup redirect

app/controllers/portfolios_controller.rb, db/seeds.rb
lot sizes from binance now save to db during seeding.
Looks like they should be converted back to float before submitting in trade order
db:drop should be performed after merging pull request
=> added lot sizes to seed file from binance

app/views/shared/_navbar.html.erb
to fix small glitch when signing up due to nav bar offering link to view portfolio before creating one
=> fixed conditional for navbar options

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_allocations.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/portfolios_controller.rb, app/javascript/components/allocation_chart.js, app/javascript/packs/application.js, app/views/allocations/create.html.erb, app/views/allocations/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/portfolios/edit.html.erb, app/views/portfolios/new.html.erb, app/views/portfolios/rebalance_positions.html.erb, app/views/shared/_allocations.html.erb, app/views/shared/_navbar.html.erb
added event listeners on allocations page to grab data from input boxes. need to get chart to load and then get chart to update automatically
=> Registration page

app/controllers/allocations_controller.rb, app/controllers/portfolios_controller.rb, app/views/portfolios/rebalance_positions.html.erb
added flash alerts to indicate rebalance / panic sell successfully completed
=> added flash alerts

app/assets/stylesheets/components/_chart.scss, app/javascript/components/portfolio_chart.js, app/views/portfolios/show.html.erb, db/seeds.rb
model defined colors now are assigned to slice in pie charts, and can be applied to anywhere in the app
=> colors from model are now assigned to correct entry in charts

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_portfolio.scss, app/controllers/allocations_controller.rb, app/controllers/application_controller.rb, app/controllers/portfolios_controller.rb, app/javascript/components/allocation_chart.js, app/javascript/components/test.js, app/javascript/packs/application.js, app/views/allocations/edit.html.erb, app/views/allocations/new.html.erb, app/views/allocations/show.html.erb, app/views/allocations/update.html.erb, app/views/devise/sessions/new.html.erb, app/views/portfolios/show.html.erb, app/views/shared/_allocations.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
updated allocations chart and a bit of css
=> Allocationschart v2

app/controllers/allocations_controller.rb, app/views/portfolios/show.html.erb, config/routes.rb
after allocations are set, the positions are automatically created before redirect to the portfolio page. also removed the button for now, as positions should be a background job
=> changed create_position route

app/controllers/portfolios_controller.rb
- Added 'price_update' method to update latest BTC price before trade executions to resolve issue of 'insufficient balance' errors returned for amounts calculated from stale BTC prices.
=> added btc price update before execution

app/controllers/portfolios_controller.rb, app/views/portfolios/show.html.erb
Added total columns to the dashboard table
=> Total columns

app/controllers/application_controller.rb, app/views/pages/user_landing.html.erb, config/routes.rb
- Created a new user landing page where they can create a new portfolio if they don't have one yet - needs more styling
- Updated sign-in path to redirect to a new home page if the user doesn't have a portfolio set up yet
=> Regression test

app/controllers/portfolios_controller.rb, db/seeds.rb
- changed  EOS min to size to 0.01 coins
- changed order confirmation to be captured in confirmations_arr << order
- renamed variable coinhash[:amount] to coinhash[:rebalance_amount]
=> updated EOS seed file

app/controllers/allocations_controller.rb, app/controllers/portfolios_controller.rb, app/models/portfolio.rb
- found logic error in rebalance loop as it was only looping coins found on the exchange portfolio.  This has been changed to iterate through the portfolio stored on the database which contains all the coins regardless of balances.
- Also added an insert_dummy_portfolio method in portfolio.rb which creates dummy placeholder positions for empty positions so that this can be referenced by the charts and table
=> added new rebalance method

app/controllers/portfolios_controller.rb, app/views/portfolios/panic_sell.html.erb
fixed error that causes panic sell not to work
=> fixed controller error

app/assets/stylesheets/components/_position.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_portfolio.scss, app/javascript/components/button_confirms.js, app/javascript/packs/application.js, app/views/portfolios/show.html.erb, package.json, yarn.lock
added modal popups for rebalance and panic sell button
changed background colour on dash board to a dark blue
=> Conf popup

app/controllers/portfolios_controller.rb, app/jobs/rebalance_portfolio_job.rb, app/models/portfolio.rb, config/sidekiq.yml, lib/tasks/scheduler.rake, test/jobs/rebalance_portfolio_job_test.rb
- Added scheduled job for rebalancing the portfolio
- Moved panic sell and rebalance processes to the portfolio model
=> Rebalance scheduled job

app/controllers/portfolios_controller.rb, app/views/orders/index.html.erb
- now saves orders after each trade execution
- logic to save base coin and target coin
=> added order saving

app/javascript/components/button_confirms.js, app/models/portfolio.rb
- Adding spinner to Rebalance and Panic Sell actions while users are waiting for those to complete
- Fix issue with portfolio controlloer
=> Adding spinner to Rebalance and Panic Sell actions

app/assets/stylesheets/pages/_allocations.scss, app/javascript/components/allocation_chart.js, app/javascript/packs/application.js, app/views/portfolios/edit.html.erb, app/views/portfolios/new.html.erb, app/views/portfolios/show.html.erb, app/views/shared/_allocations.html.erb
removed chart for timebeing in allocations edit
now a number will tell you how much you need to add remove etc
=> Allocations newest

app/assets/stylesheets/components/_chart.scss, app/assets/stylesheets/pages/_allocations.scss, app/controllers/portfolios_controller.rb, app/javascript/components/allocation_chart.js, app/javascript/packs/application.js, app/views/portfolios/edit.html.erb, app/views/shared/_allocations.html.erb
created cards for allocation entry, amounts are now calculated accurately on load and on change of input
just need to link the data to the chart so it is synced up
=> just need to link the chart

app/controllers/orders_controller.rb, app/controllers/portfolios_controller.rb, app/models/order.rb, app/models/portfolio.rb, app/views/orders/index.html.erb, app/views/portfolios/show.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20190611125310_add_transact_time_to_orders.rb, db/schema.rb
- changed schema by adding '"transact_time" to orders table
- nested orders route inside portfolio and updated paths for orders
- index.html.erb for OrdersController#index is now displaying datetime converted from unix time(milliseconds)
- Tested for both rebalance and Panic sell orders and no issues
=> added timestamp to orders

app/views/shared/_navbar.html.erb
Revised menu header for Portfolio to be a dropdown with View and Edit actions
=> Add edit portfolio button

app/assets/stylesheets/pages/_portfolio.scss, app/javascript/components/portfolio_chart.js, app/views/portfolios/show.html.erb
made bigger, and added background color
=> fixed pie chart

app/views/shared/_position.html.erb
changed 'distribution' to 'Current holdings'
changed 'target' to 'My Target'
=> changed wording on cards

app/assets/stylesheets/pages/_allocations.scss, app/assets/stylesheets/pages/_portfolio.scss, app/views/portfolios/edit.html.erb, app/views/shared/_allocations.html.erb
added some spacing to components on allocations page. forced allocation cards to 5 per row using a max-width 900px container
=> updated css spacing on allocations page

app/views/portfolios/show.html.erb
Will show in green with + symbol if it's a gain and red with a - symbol if it's a loss
=> Added percentage change to porfolio from yesterday to show page

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/filter_parameter_logging.rb, db/migrate/20190726091300_add_lockbox_to_private_key.rb, db/schema.rb, db/seeds.rb
Private Keys are now encrypted when stored to database using Lockbox gem. App still functioning, as decryption happens on the application level whenever the secret key is called.
Seed file was updated to use Binance, as the previous API had become unworkable after increasing the rate limits.
=> Encrypt private key

app/views/devise/registrations/new.html.erb
needed to add cipher text to secret key in input field
=> updated secret key input
